/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quiezel.cuenta_familiar.view;

import com.quiezel.cuenta_familiar.view.componentes.PanelUnico;
import java.awt.CardLayout;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author Chalio
 */
@Component
public class Ventana extends javax.swing.JFrame {
    private ApplicationContext context;
    private CardLayout cardLayout;

    /**
     * Creates new form ventana
     * @param context
     */
    public Ventana(ApplicationContext context) {
        initComponents();
        this.context = context;
        cardLayout = (CardLayout) panelCard.getLayout();
        addPaneles();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        panelHeader.setBackground(new java.awt.Color(204, 255, 255));
        panelHeader.setLayout(new javax.swing.BoxLayout(panelHeader, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Control Financiero");
        panelHeader.add(jLabel1);

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelCard.setBackground(new java.awt.Color(255, 255, 255));
        panelCard.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelCard, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPaneles(){
        addPanel(getBean(PanelLogin.class));
        addPanel(getBean(PanelCuentas.class));
    }
    
    public void addPanel(PanelUnico panel){
        panelCard.add(panel.getUIName(), panel);
        panel.setMostrar(c -> {
            PanelUnico panelNext = (PanelUnico)getBean(c);
            cardLayout.show(panelCard, panelNext.getUIName());//.next(panelCard);
        });
    }
    
    public <T> T getBean(Class<T> t){
        return context.getBean(t);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelCard;
    private javax.swing.JPanel panelHeader;
    // End of variables declaration//GEN-END:variables
}
